# COMANDOS IMPORTANTES DE USO:
# Para iniciar los servicios: docker-compose up -d
# Para detener los servicios: docker-compose down
# Para eliminar todo: docker-compose down -v --rmi all

services:
 

  mysql:
    image: mysql:8.1
    container_name: pelismax_mysql
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pelismax
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:

